// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: api/cat.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capsule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// айди капсулы
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// автор капсулы
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// текст капсулы
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// лейбл
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// время создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Capsule) Reset() {
	*x = Capsule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Capsule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capsule) ProtoMessage() {}

func (x *Capsule) ProtoReflect() protoreflect.Message {
	mi := &file_api_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capsule.ProtoReflect.Descriptor instead.
func (*Capsule) Descriptor() ([]byte, []int) {
	return file_api_cat_proto_rawDescGZIP(), []int{0}
}

func (x *Capsule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Capsule) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Capsule) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Capsule) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Capsule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCapsuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCapsuleRequest) Reset() {
	*x = GetCapsuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapsuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapsuleRequest) ProtoMessage() {}

func (x *GetCapsuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapsuleRequest.ProtoReflect.Descriptor instead.
func (*GetCapsuleRequest) Descriptor() ([]byte, []int) {
	return file_api_cat_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapsuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCapsuleResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Capsule `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetCapsuleResponce) Reset() {
	*x = GetCapsuleResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapsuleResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapsuleResponce) ProtoMessage() {}

func (x *GetCapsuleResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_cat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapsuleResponce.ProtoReflect.Descriptor instead.
func (*GetCapsuleResponce) Descriptor() ([]byte, []int) {
	return file_api_cat_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapsuleResponce) GetResult() *Capsule {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_cat_proto protoreflect.FileDescriptor

var file_api_cat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x23,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x44, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x70, 0x73, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x6f, 0x79, 0x61, 0x73, 0x69,
	0x2f, 0x63, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_cat_proto_rawDescOnce sync.Once
	file_api_cat_proto_rawDescData = file_api_cat_proto_rawDesc
)

func file_api_cat_proto_rawDescGZIP() []byte {
	file_api_cat_proto_rawDescOnce.Do(func() {
		file_api_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_cat_proto_rawDescData)
	})
	return file_api_cat_proto_rawDescData
}

var file_api_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_cat_proto_goTypes = []interface{}{
	(*Capsule)(nil),               // 0: api.Capsule
	(*GetCapsuleRequest)(nil),     // 1: api.GetCapsuleRequest
	(*GetCapsuleResponce)(nil),    // 2: api.GetCapsuleResponce
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_cat_proto_depIdxs = []int32{
	3, // 0: api.Capsule.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: api.GetCapsuleResponce.result:type_name -> api.Capsule
	1, // 2: api.Cat.GetCapsule:input_type -> api.GetCapsuleRequest
	2, // 3: api.Cat.GetCapsule:output_type -> api.GetCapsuleResponce
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_cat_proto_init() }
func file_api_cat_proto_init() {
	if File_api_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Capsule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapsuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapsuleResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cat_proto_goTypes,
		DependencyIndexes: file_api_cat_proto_depIdxs,
		MessageInfos:      file_api_cat_proto_msgTypes,
	}.Build()
	File_api_cat_proto = out.File
	file_api_cat_proto_rawDesc = nil
	file_api_cat_proto_goTypes = nil
	file_api_cat_proto_depIdxs = nil
}
