syntax = "proto3";

import "google/protobuf/timestamp.proto";

package api;

option go_package = "github.com/Includeoyasi/cat/pkg/grpc";

service Cat {
  rpc GetCapsule(GetCapsuleRequest) returns (GetCapsuleResponce);
  rpc CreateCapsule(CreateCapsuleRequest) returns (CreateCapsuleResponce);
  rpc DeleteCapsule(DeleteCapsuleRequest) returns (DeleteCapsuleResponce);
}

message Capsule{
  // айди капсулы
  int32 id = 1;

  // автор капсулы
  string author = 2;

  // текст капсулы
  string text = 3;

  // лейбл
  string label = 4;

  // время создания
  google.protobuf.Timestamp created_at = 5;
}

message GetCapsuleRequest{
  int32 id = 1;
}

message GetCapsuleResponce{
  Capsule result = 1;
}

message CreateCapsuleRequest{
  string author = 1;
  string text = 2;
  string label = 3;
}

message CreateCapsuleResponce{
  Capsule result = 1;
}

message DeleteCapsuleRequest{
  int32 id = 1;
}

message DeleteCapsuleResponce{
  bool deleted = 1;
}
